# Generated by Django 6.0.1 on 2026-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='ach1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='ach2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='ach3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='college2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='college3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='company1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='company2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='desc1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='desc2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='durat1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='durat2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='duration1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='duration2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='lang1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='lang2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='lang3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='lin11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='lin21',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='post1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='post2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='project1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='project2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='year2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='year3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='college1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
